language: php

sudo: false

php:
    - "7.1"
    - "7.2"
    - "nightly"

env:
    global:
        - COMPOSER_MEMORY_LIMIT=-1

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

services: postgresql

before_install:
    - psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
    - psql -c 'CREATE TABLE config (name character varying(25) PRIMARY KEY, value character varying(25), status integer default 1)' -U postgres -h 127.0.0.1 pomm_test
    - psql -c 'CREATE TABLE filter (name character varying(25) PRIMARY KEY, value character varying(25), value_partial character varying(25), value_start character varying(25), value_end character varying(25), value_word_start character varying(25), value_ipartial character varying(25))' -U postgres -h 127.0.0.1 pomm_test

    - php -S localhost:8080 -t test/web &> /dev/null &
    - ln -fs parameters.yml.dist test/app/config/parameters.yml

install:
    - composer install
    - cd test/
    - composer update
    - rm -rf vendor/pomm-project/api-platform
    - ln -s ../../../ vendor/pomm-project/api-platform

script:
    - ./bin/behat
